### ISSUE TITLE
FE: Itinerary Page

### ISSUE THREAD

**Issue by LeahWinters** [To-the-Moon-and-Back/to-the-moon-and-back#9]
**As a user, when I select which destination I want to travel to, I should see the header we already created and a form that asks me:**

- [x] How many Earth days I want to spend at the destination
- [x] How many people am I traveling with. This should be a drop down containing the numbers 1 through 5.

**Once the user selects the number of people they want to travel with, the user should see a form pop up for each person that is going on the voyage. Each form should ask for:** 

- [x] Their name
- [x] Their age
- [x] Their weight in pounds

**Once the user fills out all inputs on the page they can:**

- [x] click a button found at the bottom of the page called 'Start My Voyage!'

**If the user does not fill out all inputs on the form, they should see:** 

- [x] An error message asking them to please complete all parts of the form

**Comment by lilianaweimer** [comment]
Found a bug with how we are using the `Link`. It's possible to click on it and instantly travel without filling the form out. I think that we should try using a `Redirect` inside of the `onClick()` to get around this.
